### ISSUE TITLE
Questions on saving images

### ISSUE THREAD

**Issue by cblake777** [andygrundman/Image-Scale#4]
I noticed that the methods for saving images (at least according to the documentation I've read so far) all involve saving to an alternate file as well as knowing what format I want to write it as.

Is there a way to 'overwrite' the file that was opened in the first place? For example, say I have a batch operation on a set of files where I know the files are valid images (gif, jpeg, png), open the file, resize them, and then just immediately save the resized file, without needing to know name / location or type? 

Thanks!
Carl Blakemore

**Comment by andygrundman** [comment]
Thanks for the suggestion. This sounds like a fairly dangerous feature though, what if something goes wrong and you lose your original file? What if you later decide you should have resized to a different size? If you are sure you want to do this, how about something like this. write_file will overwrite the original file by using the in-memory resize option as_jpeg (or as_png).

```
use File::Slurp qw(write_file);
use Image::Scale;

for my $file ( @files ) {
    my $img = Image::Scale->new($file) || die "Invalid file";
    $img->resize( { width => 100 } );
    write_file( $file, \($img->as_jpeg) ) || die "Unable to write to $file";
}
```

**Comment by cblake777** [comment]
Now that I've had further time to think about it (at the time I was dealing with a something imploding due to image magick issues), I think this suggestion will work perfectly fine. 

Thanks!
